In [1]:
import pandas as pd
import numpy as np
import os

In [2]:
os.getcwd()

'C:\\Users\\USER\\Downloads\\House_Prices_Prediction'

In [3]:
df1 = pd.read_csv('./House for rent.csv')

In [4]:
df2 = pd.read_csv('./Properties.csv')

In [5]:
df1.head()

page                                        description  \
0     1              5 Bedrooms Detached House + 1 Room BQ   
1     1       Nice 3 Bedroom Apartment in a Secured Estate   
2     1  Luxury Flats and Apartments along Banana Islan...   
3     1    Luxury 3 Bedroom Flat with Excellent Facilities   
4     1  Direct Payment Ready Clients - Waterfront 3 Be...   

                        title  bedrooms  bathrooms  garage  \
0             5 Bedroom House         5          5       0   
1  3 Bedroom Flat & Apartment         3          3       0   
2  3 Bedroom Flat & Apartment         3          3       0   
3  3 Bedroom Flat & Apartment         3          3       0   
4  3 Bedroom Flat & Apartment         3          3       2   

                                          location   city     price       type  
0         Joel Ogunnaike Street Gra, Ikeja , Ikeja  Ikeja   7500000      House  
1                             Banana Island, Ikoyi  Ikoyi  15000000  Apartment  
2  Banana Island Road, Ikoyi, Banana Island, Ikoyi  Ikoyi  15000000  Apartment  
3                                            Ikoyi  Ikoyi  10000000  Apartment  
4       Banana Island Estate, Banana Island, Ikoyi  Ikoyi  16000000  Apartment

In [6]:
df1.dtypes

page            int64
description    object
title          object
bedrooms        int64
bathrooms       int64
garage          int64
location       object
city           object
price           int64
type           object
dtype: object

In [7]:
df1['bedrooms'].unique()

array([  5,   3,   4,   2,   0,   1,   6,  44,  12,   7,  10,  19,  20,
        16, 400,  15,   9], dtype=int64)

In [8]:
df1 = df1[~(df1['bedrooms']>7)]

In [9]:
df1['bedrooms'].unique()

array([5, 3, 4, 2, 0, 1, 6, 7], dtype=int64)

In [10]:
df1 = df1[~(df1['bathrooms']>8)]

In [11]:
df1['bathrooms'].unique()

array([5, 3, 4, 2, 0, 1, 6, 7, 8], dtype=int64)

In [14]:
df1[df1['bathrooms']==0]['title'].unique()

array(['Office', 'Commercial Property', 'Warehouse', 'Hotel',
       '3 Bedroom Flat & Apartment', 'Shop', 'Room or Boys Quarter',
       '4 Bedroom Terrace', 'Duplex', 'Flat & Apartment', 'Land',
       'Terrace', 'Bungalow'], dtype=object)

In [193]:
df1['bedrooms'].unique()

array([5, 3, 4, 2, 0, 1, 6, 7], dtype=int64)

In [194]:
def toilets(df1):
    if df1['bathrooms'] == 0:
        return 1
    if df1['bathrooms'] == 1:
        return 2
    if df1['bathrooms'] == 2:
        return 3
    if df1['bathrooms'] == 3:
        return 4
    if df1['bathrooms'] == 4:
        return 5
    if df1['bathrooms'] == 5:
        return 6
    if df1['bathrooms'] == 6:
        return 7
    if df1['bathrooms'] == 7:
        return 8
    else:
        return 9

In [195]:
df1['toilets'] = df1.apply(toilets, axis=1)

In [196]:
df1['garage'] = df1['toilets']

In [197]:
df1.drop('toilets', axis=1,inplace=True)

In [198]:
df1.rename(columns={'garage':'toilets'},inplace=True)

In [199]:
df1.head()

page                                        description  \
0     1              5 Bedrooms Detached House + 1 Room BQ   
1     1       Nice 3 Bedroom Apartment in a Secured Estate   
2     1  Luxury Flats and Apartments along Banana Islan...   
3     1    Luxury 3 Bedroom Flat with Excellent Facilities   
4     1  Direct Payment Ready Clients - Waterfront 3 Be...   

                        title  bedrooms  bathrooms  toilets  \
0             5 Bedroom House         5          5        6   
1  3 Bedroom Flat & Apartment         3          3        4   
2  3 Bedroom Flat & Apartment         3          3        4   
3  3 Bedroom Flat & Apartment         3          3        4   
4  3 Bedroom Flat & Apartment         3          3        4   

                                          location   city     price       type  
0         Joel Ogunnaike Street Gra, Ikeja , Ikeja  Ikeja   7500000      House  
1                             Banana Island, Ikoyi  Ikoyi  15000000  Apartment  
2  Banana Island Road, Ikoyi, Banana Island, Ikoyi  Ikoyi  15000000  Apartment  
3                                            Ikoyi  Ikoyi  10000000  Apartment  
4       Banana Island Estate, Banana Island, Ikoyi  Ikoyi  16000000  Apartment

In [200]:
df2.head()

page                                           title  \
0     1  An Exquisite And Luxurious 3 Bedroom Apartment   
1     1                              2bedroom Apartment   
2     1     Executive 3 Bedroom Flat Serviced Apartment   
3     1                   Fantastic 1 Bedroom Mini Flat   
4     1                                          Luxury   

                                       description  bedrooms  bathrooms  \
0              3 bedroom flat / apartment for rent         3          3   
1              2 bedroom flat / apartment for rent         2          2   
2              3 bedroom flat / apartment for rent         3          3   
3  1 bedroom mini flat (room and parlour) for rent         1          1   
4              4 bedroom flat / apartment for rent         4          3   

   toilets  garage                                   location  \
0        4       3                               Ikoyi, Lagos   
1        3       0  Oniru, Oniru, Victoria Island (VI), Lagos   
2        3       2    Prime Water Garden, Ikate, Lekki, Lagos   
3        1       0               Lekki Palm City, Ajah, Lagos   
4        4       0                    Old Ikoyi, Ikoyi, Lagos   

              city     price  
0            Ikoyi  15000000  
1  Victoria Island   3500000  
2            Lekki   4000000  
3             Ajah   1000000  
4            Ikoyi  12000000

In [201]:
df1.drop(['page','type',], axis=1, inplace=True)

In [202]:
df2.drop(['page','garage'],axis=1, inplace=True)

In [203]:
df1.head()

description  \
0              5 Bedrooms Detached House + 1 Room BQ   
1       Nice 3 Bedroom Apartment in a Secured Estate   
2  Luxury Flats and Apartments along Banana Islan...   
3    Luxury 3 Bedroom Flat with Excellent Facilities   
4  Direct Payment Ready Clients - Waterfront 3 Be...   

                        title  bedrooms  bathrooms  toilets  \
0             5 Bedroom House         5          5        6   
1  3 Bedroom Flat & Apartment         3          3        4   
2  3 Bedroom Flat & Apartment         3          3        4   
3  3 Bedroom Flat & Apartment         3          3        4   
4  3 Bedroom Flat & Apartment         3          3        4   

                                          location   city     price  
0         Joel Ogunnaike Street Gra, Ikeja , Ikeja  Ikeja   7500000  
1                             Banana Island, Ikoyi  Ikoyi  15000000  
2  Banana Island Road, Ikoyi, Banana Island, Ikoyi  Ikoyi  15000000  
3                                            Ikoyi  Ikoyi  10000000  
4       Banana Island Estate, Banana Island, Ikoyi  Ikoyi  16000000

In [204]:
df2.head()

title  \
0  An Exquisite And Luxurious 3 Bedroom Apartment   
1                              2bedroom Apartment   
2     Executive 3 Bedroom Flat Serviced Apartment   
3                   Fantastic 1 Bedroom Mini Flat   
4                                          Luxury   

                                       description  bedrooms  bathrooms  \
0              3 bedroom flat / apartment for rent         3          3   
1              2 bedroom flat / apartment for rent         2          2   
2              3 bedroom flat / apartment for rent         3          3   
3  1 bedroom mini flat (room and parlour) for rent         1          1   
4              4 bedroom flat / apartment for rent         4          3   

   toilets                                   location             city  \
0        4                               Ikoyi, Lagos            Ikoyi   
1        3  Oniru, Oniru, Victoria Island (VI), Lagos  Victoria Island   
2        3    Prime Water Garden, Ikate, Lekki, Lagos            Lekki   
3        1               Lekki Palm City, Ajah, Lagos             Ajah   
4        4                    Old Ikoyi, Ikoyi, Lagos            Ikoyi   

      price  
0  15000000  
1   3500000  
2   4000000  
3   1000000  
4  12000000

In [205]:
df1.rename(columns={
    'description':'title',
    'title':'description'
}, inplace=True)

In [206]:
df1.head()

title  \
0              5 Bedrooms Detached House + 1 Room BQ   
1       Nice 3 Bedroom Apartment in a Secured Estate   
2  Luxury Flats and Apartments along Banana Islan...   
3    Luxury 3 Bedroom Flat with Excellent Facilities   
4  Direct Payment Ready Clients - Waterfront 3 Be...   

                  description  bedrooms  bathrooms  toilets  \
0             5 Bedroom House         5          5        6   
1  3 Bedroom Flat & Apartment         3          3        4   
2  3 Bedroom Flat & Apartment         3          3        4   
3  3 Bedroom Flat & Apartment         3          3        4   
4  3 Bedroom Flat & Apartment         3          3        4   

                                          location   city     price  
0         Joel Ogunnaike Street Gra, Ikeja , Ikeja  Ikeja   7500000  
1                             Banana Island, Ikoyi  Ikoyi  15000000  
2  Banana Island Road, Ikoyi, Banana Island, Ikoyi  Ikoyi  15000000  
3                                            Ikoyi  Ikoyi  10000000  
4       Banana Island Estate, Banana Island, Ikoyi  Ikoyi  16000000

In [207]:
prop = pd.concat([df1,df2],ignore_index=True)

In [208]:
prop

title  \
0                 5 Bedrooms Detached House + 1 Room BQ   
1          Nice 3 Bedroom Apartment in a Secured Estate   
2     Luxury Flats and Apartments along Banana Islan...   
3       Luxury 3 Bedroom Flat with Excellent Facilities   
4     Direct Payment Ready Clients - Waterfront 3 Be...   
...                                                 ...   
9974                        Luxurious Self Contain Room   
9975            Very Big And Spacious Self Contain Room   
9976  Newly Built, Pop Finishing. Upstairs & Downstairs   
9977                 Luxury Spacious Penthouse Miniflat   
9978    Well Maintained Studio Apartment With Generator   

                                          description  bedrooms  bathrooms  \
0                                     5 Bedroom House         5          5   
1                          3 Bedroom Flat & Apartment         3          3   
2                          3 Bedroom Flat & Apartment         3          3   
3                          3 Bedroom Flat & Apartment         3          3   
4                          3 Bedroom Flat & Apartment         3          3   
...                                               ...       ...        ...   
9974             Self contain (single rooms) for rent         0          1   
9975              1 bedroom flat / apartment for rent         1          1   
9976             Self contain (single rooms) for rent         0          1   
9977  1 bedroom mini flat (room and parlour) for rent         1          1   
9978             Self contain (single rooms) for rent         0          1   

      toilets                                           location      city  \
0           6           Joel Ogunnaike Street Gra, Ikeja , Ikeja     Ikeja   
1           4                               Banana Island, Ikoyi     Ikoyi   
2           4    Banana Island Road, Ikoyi, Banana Island, Ikoyi     Ikoyi   
3           4                                              Ikoyi     Ikoyi   
4           4         Banana Island Estate, Banana Island, Ikoyi     Ikoyi   
...       ...                                                ...       ...   
9974        1                        Lekki Phase 1, Lekki, Lagos     Lekki   
9975        1              Unity Estate, Egbeda, Alimosho, Lagos  Alimosho   
9976        1               Rockstone Ville Estate, Lekki, Lagos     Lekki   
9977        1  Atlantic View Estate Alpha Beach Road, Lekki, ...     Lekki   
9978        1                        Lekki Phase 1, Lekki, Lagos     Lekki   

         price  
0      7500000  
1     15000000  
2     15000000  
3     10000000  
4     16000000  
...        ...  
9974    800000  
9975    230000  
9976    300000  
9977   1600000  
9978   1300000  

[9979 rows x 8 columns]

In [209]:
prop.isnull().sum()

title          0
description    0
bedrooms       0
bathrooms      0
toilets        0
location       0
city           0
price          0
dtype: int64

In [210]:
prop.to_csv('Properties1.csv', index=False)

In [211]:
prop['bedrooms'].unique()

array([5, 3, 4, 2, 0, 1, 6, 7, 8], dtype=int64)